export const REGISTRATION = 'REGISTRATION';
export const REGISTRATION_PENDING = 'REGISTRATION_PENDING';
export const REGISTRATION_FULFILLED = 'REGISTRATION_FULFILLED';
export const REGISTRATION_REJECTED = 'REGISTRATION_REJECTED';

export const QUESTION = 'QUESTION';
export const QUESTION_PENDING = 'QUESTION_PENDING';
export const QUESTION_FULFILLED = 'QUESTION_FULFILLED';
export const QUESTION_REJECTED = 'QUESTION_REJECTED';

export const ANSWER = 'ANSWER';
export const ANSWER_FULFILLED = 'ANSWER_FULFILLED';
export const ANSWER_REJECTED = 'ANSWER_REJECTED';
