export const REGISTRATION = 'REGISTRATION';
export const REGISTRATION_FULFILLED = 'REGISTRATION_FULFILLED'
export const REGISTRATION_REJECTED = 'REGISTRATION_REJECTED'

export const QUESTION = 'QUESTION';
export const QUESTION_FULFILLED = 'QUESTION_FULFILLED'
export const QUESTION_REJECTED = 'QUESTION_REJECTED'